//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseServer.WarehouseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WarehouseService.IWarehouseService", CallbackContract=typeof(WarehouseServer.WarehouseService.IWarehouseServiceCallback))]
    public interface IWarehouseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/GetOpenRequests", ReplyAction="http://tempuri.org/IWarehouseService/GetOpenRequestsResponse")]
        System.Data.DataTable GetOpenRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/GetOpenRequests", ReplyAction="http://tempuri.org/IWarehouseService/GetOpenRequestsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOpenRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/AddRequest", ReplyAction="http://tempuri.org/IWarehouseService/AddRequestResponse")]
        int AddRequest(string title, int quantity, System.DateTime sent, System.DateTime received, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/AddRequest", ReplyAction="http://tempuri.org/IWarehouseService/AddRequestResponse")]
        System.Threading.Tasks.Task<int> AddRequestAsync(string title, int quantity, System.DateTime sent, System.DateTime received, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/ShipRequest", ReplyAction="http://tempuri.org/IWarehouseService/ShipRequestResponse")]
        int ShipRequest(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/ShipRequest", ReplyAction="http://tempuri.org/IWarehouseService/ShipRequestResponse")]
        System.Threading.Tasks.Task<int> ShipRequestAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/Subscribe", ReplyAction="http://tempuri.org/IWarehouseService/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/Subscribe", ReplyAction="http://tempuri.org/IWarehouseService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/Unsubscribe", ReplyAction="http://tempuri.org/IWarehouseService/UnsubscribeResponse")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/Unsubscribe", ReplyAction="http://tempuri.org/IWarehouseService/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWarehouseServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWarehouseService/OnCallback", ReplyAction="http://tempuri.org/IWarehouseService/OnCallbackResponse")]
        void OnCallback();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWarehouseServiceChannel : WarehouseServer.WarehouseService.IWarehouseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseServiceClient : System.ServiceModel.DuplexClientBase<WarehouseServer.WarehouseService.IWarehouseService>, WarehouseServer.WarehouseService.IWarehouseService {
        
        public WarehouseServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WarehouseServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WarehouseServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetOpenRequests() {
            return base.Channel.GetOpenRequests();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOpenRequestsAsync() {
            return base.Channel.GetOpenRequestsAsync();
        }
        
        public int AddRequest(string title, int quantity, System.DateTime sent, System.DateTime received, int orderId) {
            return base.Channel.AddRequest(title, quantity, sent, received, orderId);
        }
        
        public System.Threading.Tasks.Task<int> AddRequestAsync(string title, int quantity, System.DateTime sent, System.DateTime received, int orderId) {
            return base.Channel.AddRequestAsync(title, quantity, sent, received, orderId);
        }
        
        public int ShipRequest(int id) {
            return base.Channel.ShipRequest(id);
        }
        
        public System.Threading.Tasks.Task<int> ShipRequestAsync(int id) {
            return base.Channel.ShipRequestAsync(id);
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync() {
            return base.Channel.UnsubscribeAsync();
        }
    }
}
